### ISSUE TITLE
Create html outline

### ISSUE THREAD

**Issue by shiryz** [shiryz/nazareth-tour-guide#1]
- [x] nav bar 
- [x] about section
- [x] tours section
- [x] footer

**Comment by Karyum** [comment]
so again the tours section has links to couple of tours around Israel? is something like this fine ?
![screenshot from 2017-06-21 15-36-51](https://user-images.githubusercontent.com/24195641/27384498-ba5e1a5a-5697-11e7-860f-929fca5e5175.png)
